#ifndef __ChecksumDialog__
#define __ChecksumDialog__

/**
@file
Subclass of ChecksumDialogBase, which is generated by wxFormBuilder.
*/

#include "Dialogs.h"

/** Implementing ChecksumDialogBase */
class ChecksumDialog : public ChecksumDialogBase
{
public:
	/** Constructor */
	ChecksumDialog( wxWindow* parent );
	virtual ~ChecksumDialog();

    void SetAlgoName(const wxString& sAlgoName);
    void SetChecksumValues(const wxString& sLuma, const wxString& sChroma);
};

#endif // __ChecksumDialog__
