#ifndef __GridSettingsDialog__
#define __GridSettingsDialog__

/**
@file
Subclass of GridDialogBase, which is generated by wxFormBuilder.
*/

#include "Dialogs.h"

/** Implementing GridDialogBase */
class GridSettingsDialog : public GridDialogBase
{
public:
    /** Constructor */
    GridSettingsDialog( wxWindow* parent );
};

#endif // __GridSettingsDialog__
