#ifndef __SizeDialog__
#define __SizeDialog__

/**
@file
Subclass of SizeDialogBase, which is generated by wxFormBuilder.
*/

#include "Dialogs.h"

class Frame;

/** Implementing SizeDialogBase */
class SizeDialog : public SizeDialogBase
{
public:
	/** Constructor */
	SizeDialog( wxWindow* parent, int width, int height );

	//friend class Frame;
};

#endif // __SizeDialog__
