#ifndef __SizeDialog__
#define __SizeDialog__

/**
@file
Subclass of SizeDialogBase, which is generated by wxFormBuilder.
*/

#include "Dialogs.h"

class Frame;

enum videoStd {
    STD_CUSTOM,
    STD_SQCIF,
    STD_QCIF,
    STD_SCIF,
    STD_SIF,
    STD_CIF,
    STD_VGA,
    STD_4SIF,
    STD_4CIF,
    STD_SVGA,
    STD_SXGA,
    STD_1080p,
};

struct vidstd_entry {
    videoStd        standard;
    int             width;
    int             height;
};

/** Implementing SizeDialogBase */
class SizeDialog : public SizeDialogBase
{
public:
	/** Constructor */
	SizeDialog( wxWindow* parent, int width, int height );

    void OnChangeStandard( wxCommandEvent& event );

    void    GetFrameDimensions(long& width, long& height);

protected:

    void    SetStandardToDimensions(int width, int height);
    void    SetDimensionsToStandard(videoStd standard);
	//friend class Frame;
};

#endif // __SizeDialog__
