#ifndef __YUVSplitDialog__
#define __YUVSplitDialog__

/**
@file
Subclass of YUVSplitDialogBase, which is generated by wxFormBuilder.
*/

#include "Dialogs.h"
#include "misc_utils.h"
#include "imageBuffer.h"
#include "YUV420ImageBufferSplit.h"

/** Implementing YUVSplitDialogBase */
class YUVSplitDialog : public YUVSplitDialogBase
{
public:
	/** Constructor */
	YUVSplitDialog( wxWindow* parent );


    void    SetDialogOptions(const wxSize               frameSize,
                             const YUV420ImageSpec&     imagespec,
                             const wxUint16             bits    = 8,
                             const formatEndian         fmt     = endian_little,
                             const dataType             yuvFmt  = DATA_YUV420);
//    void    SetDialogOptions(const wxSize               frameSize,
//                             const wxString             sPath,
//                             const wxString             sPrefix,
//                             const wxUint16             bits    = 8,
//                             const formatEndian         fmt     = endian_little,
//                             const dataType             yuvFmt  = DATA_YUV420);


    void    GetFrameDimensions(wxSize& frameSize);
    void    GetFrameDimensions(long& width, long& height);
    void    GetFrameBits(wxUint16& bits);
    void    GetFrameEndianness(formatEndian& endian);
    void    GetFrameYUVFmt(dataType& yuvFmt);
    void    GetFileInfo(wxString& sFilePath, wxString& sFilePrefix);
    void    GetFrameVector(utils::FRAME_FILEBASE_VEC& vec);
    void    GetImageSpec(YUV420ImageSpec& spec);

protected:
    void    SetDialogOptions();

	// Handlers for YUVSplitDialogBase events.
    void    OnInitDialog(wxInitDialogEvent& event)      override;

	void    OnUpdateUI( wxUpdateUIEvent& event )        override;
	void    OnPrefixChanged( wxCommandEvent& event )    override;
	void    OnDirChanged( wxFileDirPickerEvent& event ) override;
	void    OnChangeStandard( wxCommandEvent& event )   override;

    void    SetStandardToDimensions(int width, int height);

    bool ValidateFileSpec();

private:

    wxSize          m_frameSize;
    YUV420ImageSpec m_spec;
//    wxString        m_sPath;
//    wxString        m_sPrefix;
    wxUint32        m_bits;
    formatEndian    m_endian;
    dataType        m_yuvFmt;

    utils::FRAME_FILEBASE_VEC   m_fileVec;
};

#endif // __YUVSplitDialog__
